FROM python:3.11-slim
WORKDIR /app
COPY requirements_frontend.txt .
RUN pip install --no-cache-dir -r requirements_frontend.txt
COPY backend.py . 
COPY frontend.py .
# On crée le dossier data pour le volume
RUN mkdir data
EXPOSE 8050
CMD ["python", "frontend.py"]
