FROM python:3.11-slim

WORKDIR /app
# Copy requirements.txt first for caching efficiency
COPY requirements_frontend.txt .
RUN pip install --no-cache-dir -r requirements_frontend.txt

ENV PYTHONUNBUFFERED=1

CMD ["python", "frontend.py"]
