FROM python:3.11-slim
WORKDIR /app
COPY requirements_backend.txt .
RUN pip install --no-cache-dir -r requirements_backend.txt
COPY backend.py .
# On ne copie pas le JSON, il sera monté en volume
CMD ["python", "backend.py"]
